[package]
name = "serde_yaml"
version = "0.7.0" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "YAML support for Serde"
repository = "https://github.com/dtolnay/serde-yaml"
documentation = "https://docs.rs/serde_yaml/"
readme = "README.md"
keywords = ["yaml", "serde"]

[dependencies]
linked-hash-map = "0.4"
num-traits = "0.1.37"
serde = "1.0"
yaml-rust = { git = "https://github.com/chyh1990/yaml-rust", rev = "efbe0d583e9673d95a5b4fa575bfdebcf288cd77" }

[dev-dependencies]
serde_derive = "1.0"
unindent = "0.1"
